<a href="https://colab.research.google.com/github/OscarIvaVP/Analisis-Descriptivo-Python/blob/main/Analisis-datos-empresa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd

# Load the data from the provided Excel file
data = pd.read_excel("Datos.xlsx")

# Display the first few rows to understand the structure of the dataset
data.head()

     Sexo  Edad  Experiencia  Salario
0  Hombre    45           10  4390146
1   Mujer    23            3  1837736
2   Mujer    32            5  3055596
3  Hombre    42           12  1184036
4  Hombre    25            5  3638265

In [7]:
# 2. Select only numeric columns from the dataset
numeric_data = data.select_dtypes(include=['number'])
# 3. Calculate descriptive statistics for the numeric columns
desc_stats_auto = numeric_data.describe()
# Add the mode to the descriptive statistics
modes_auto = numeric_data.mode().loc[0]
desc_stats_auto = desc_stats_auto.append(pd.Series(modes_auto, name='Moda'))
# 4. Round the descriptive statistics to two significant figures
desc_stats_rounded = desc_stats_auto.round(2)
desc_stats_rounded

<ipython-input-7-0dc5bf9da7e4>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  desc_stats_auto = desc_stats_auto.append(pd.Series(modes_auto, name='Moda'))

        Edad  Experiencia     Salario
count  25.00        25.00       25.00
mean   28.52         6.44  2906802.16
std     8.73         4.76  1238558.29
min    17.00         1.00  1184036.00
25%    23.00         3.00  1559609.00
50%    27.00         5.00  3055596.00
75%    33.00        10.00  4112614.00
max    52.00        20.00  4469627.00
Moda   23.00         5.00  1184036.00

In [12]:
# Calcular frecuencia absoluta
freq_abs_sex = data["Sexo"].value_counts()
# Calcular frecuencia relativa
freq_rel_sex = data["Sexo"].value_counts(normalize=True)
# Crear tabla de frecuencia
tabla_freq_sex = pd.DataFrame({"Frecuencia absoluta": freq_abs_sex, "Frecuencia relativa": freq_rel_sex})
print(tabla_freq_sex)

        Frecuencia absoluta  Frecuencia relativa
Mujer                    16                 0.64
Hombre                    9                 0.36

In [13]:
# Definir categorías de edad
data["Categoría Edad"] = ["Mayor de 22 años" if edad > 22 else "Menor o igual a 22 años" for edad in data["Edad"]]
# Calcular frecuencia absoluta
freq_abs_age = data["Categoría Edad"].value_counts()
# Calcular frecuencia relativa
freq_rel_age = data["Categoría Edad"].value_counts(normalize=True)
# Crear tabla de frecuencia
tabla_freq_age = pd.DataFrame({"Frecuencia absoluta": freq_abs_age, "Frecuencia relativa": freq_rel_age})
print(tabla_freq_age)

                         Frecuencia absoluta  Frecuencia relativa
Mayor de 22 años                          19                 0.76
Menor o igual a 22 años                    6                 0.24

In [14]:
# Definir categorías de salario
data["Categoría Salario"] = ["Salario mayor a 2,000,000" if salario > 2000000 else "Salario menor o igual a 2,000,000" for salario in data["Salario"]]
# Calcular frecuencia absoluta
freq_abs_salary = data["Categoría Salario"].value_counts()
# Calcular frecuencia relativa
freq_rel_salary = data["Categoría Salario"].value_counts(normalize=True)
# Crear tabla de frecuencia
tabla_freq_salary = pd.DataFrame({"Frecuencia absoluta": freq_abs_salary, "Frecuencia relativa": freq_rel_salary})
print(tabla_freq_salary)

                                   Frecuencia absoluta  Frecuencia relativa
Salario mayor a 2,000,000                           15                  0.6
Salario menor o igual a 2,000,000                   10                  0.4